language: node_js
node_js:
 - "8"
before_script:
 - npm install -g gulp-cli
script:
 - gulp
 - gulp test-only
stage:
 - build
 - release    
jobs:
 include:
  - stage: build
    if: brach != master
  - stage: release
    if: brach = master
    node_js: "8"
    script: echo "Publishing..."
    deploy:
       provider: npm
       api_key: "$NPM_API_KEY"
       email: "$NPM_EMAIL"
       on:
         tags: true
 
notifications:
  email:
    on_success: never
    on_failure: never
