language: node_js
node_js:
 - "8"
before_script:
 - npm install -g gulp-cli
 - npm run build
script:
 - npm run test-only
after_success:
 - npm pack 
stage:
 - build
 - release
jobs:
 include:
  - stage: build
    if: branch != master
  - stage: release
    if: branch = master
    node_js: "8"    
deploy:
  provider: npm
  api_key: "$NPM_API_KEY"
  email: "$NPM_EMAIL"
  skip_cleanup: true
  on:
    tags: true
    branch: master
 
notifications:
  email:
    on_success: never
    on_failure: never
